language: groovy
jdk:
- oraclejdk8
sudo: false
branches:
  only:
  - master
before_install:
 - wget -q https://raw.githubusercontent.com/AtlasOfLivingAustralia/travis-build-configuration/master/ala_common.sh
 - chmod +x ala_common.sh
 - source ./ala_common.sh
 - ala_travis_grails_setup_env
script:
 - ala_travis_grails_build
env:
  global:
  - secure: hoYu5PwbsNn2uY/RhAG1jx+rKqqFihc191dm9ckybeJ1GOSICm5dzZX1a/FRZzfnoqontjyuAJl+CLvAsYpCHB8CAHChGdBlHF8QtaTL8dfIFmq/Wc5ogrgLSDollltbyYlorR/RhDklOuN3dOe8fz06Uk7HpjWW5E2jAzq6PSY=
  - secure: Zlep5iq5qvAk72LiSRlcwI0BYHp0sDdm/iyDp/umVNCVA4/jzPdmf+Mml9gmyiR9sJwVwA5/AeyTcKsO/FXTEnfHYDtCbXOptHj84m8pQ93OlrD2e0tndpzg7oVwRmj9dJeBPu61XcxPRfXuPRy6C1++kR36ZcAIKqApOArT0EI=
