---
grails:
    profile: web
    config:
      locations:
        - file:///data/sds/config/sds-config.properties
        - file:///data/sds/config/sds-config.yml
        - file:///data/sds/config/sds-config.groovy
    codegen:
        defaultPackage: au.org.ala.sds
    spring:
        transactionManagement:
            proxies: false
    gorm:
        # Whether to autowire entities.
        # Disabled by default for performance reasons.
        autowire: false
        reactor:
            # Whether to translate GORM events into Reactor events
            # Disabled by default for performance reasons
            events: false
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false
  # Spring Actuator Endpoints are Disabled by Default
    jmx:
      unique-names: true
    management:
      endpoints:
        enabled-by-default: false
    devtools:
      restart:
        exclude:
          - grails-app/views/**
          - grails-app/i18n/**
          - grails-app/conf/**

---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlets: html
                taglib: none
                staticparts: none

---
#Required so that the gbif-ecat library does not bugger up initialisation from its internal application.properties
app:
  dataDir: /tmp/gbif-ecat
serverName: https://sds.ala.org.au
security:
  cas:
    enabled: false
    appServerName: https://sds.ala.org.au
    casServerName: https://auth.ala.org.au
    uriFilterPattern: /refresh
    authenticateOnlyIfLoggedInPattern: '/.*'
    uriExclusionFilterPattern: '/*.xml'
    loginUrl: https://auth.ala.org.au/cas/login
    logoutUrl: https://auth.ala.org.au/cas/logout
    casServerUrlPrefix: https://auth.ala.org.au/cas
    bypass: false
  oidc:
    enabled: true
    discoveryUri: https://auth-test.ala.org.au/cas/oidc/.well-known
    scope: openid profile email ala roles
  jwt:
    enabled: true
    discoveryUri: https://auth-test.ala.org.au/cas/oidc/.well-known
    fallbackToLegacyBehaviour: true


sdsFAQ:
    url: https://www.ala.org.au/faq/data-sensitivity/
lists:
    tool:
        url: https://lists.ala.org.au
sandbox:
    url: https://sandbox.ala.org.au

openapi:
  title: SDS REST services
  description: SDS services for interacting with the SDS webapp
  terms: https://www.ala.org.au/terms-of-use
  contact:
    name: Support
    email: support@ala.org.au
  license:
    name: Mozilla Public License 1.1
    url: https://www.mozilla.org/en-US/MPL/1.1/
  version: '@info.app.version@'
  cachetimeoutms: 0
